# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: dev-setup
description: Mi setup optimizado para el desarrollo y entretenimiento

base-image: ghcr.io/wayblueorg/hyprland-nvidia-open:latest
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-$(rpm -E %fedora)/atim-starship-fedora-$(rpm -E %fedora).repo
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-$(rpm -E %fedora)/bieszczaders-kernel-cachyos-fedora-$(rpm -E %fedora).repo
    install:
      - cloudflare-warp
      - code
      - kernel-cachyos-rt
    remove:
      - firefox
      - firefox-langpacks
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-core
      - kernel-modules-extra
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.brave.Browser
        - com.google.ChromeDev
        - com.valvesoftware.Steam
        - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        - com.heroicgameslauncher.hgl
        - com.usebottles.bottles
        - io.podman_desktop.PodmanDesktop
      remove:
        - org.gnome.eog

  - type: signing
